更改配置文件存储类型为数据库
Jinxuyang/arros pull request #1
Opened 2021-11-13 03:14 UTC by zero-face

2021-11-14 05:16 UTC, Jinxuyang requested changes
:)

2021-11-14 05:16 UTC, Jinxuyang commented on modules/server/src/main/java/cn/arros/server/entity/SysConfig.java
> +    private String config_key;
保持风格统一，都使用小驼峰

2021-11-14 05:16 UTC, Jinxuyang commented on modules/server/src/main/java/cn/arros/server/entity/SysConfig.java
> +    private Integer config_id;
保持风格统一，都使用小驼峰

2021-11-14 05:16 UTC, Jinxuyang commented on modules/server/src/main/java/cn/arros/server/entity/SysConfig.java
> +    private Date gmtCreate;
gmt是什么意思？
为保证风格统一，改为createTime

2021-11-14 05:16 UTC, Jinxuyang commented on modules/server/src/main/java/cn/arros/server/entity/SysConfig.java
> +    private Date gmtModified;
为保证风格统一，改为updateTime

2021-11-14 05:16 UTC, Jinxuyang commented on modules/server/src/main/java/cn/arros/server/entity/SysConfig.java
> +    @TableField(fill = FieldFill.UPDATE)
可以去除

2021-11-14 05:16 UTC, Jinxuyang commented on modules/server/src/main/java/cn/arros/server/entity/SysConfig.java
> +    @TableField(fill = FieldFill.INSERT)
可以去除

2021-11-14 05:16 UTC, Jinxuyang commented on modules/server/src/main/java/cn/arros/server/properties/ArrosProperties.java
> +    public SysConfig getConfig(ConfigType type) {
这样写是不是每次获取配置都要读数据库，有点低效。
是否可以写成项目启动时从数据读取，之后可以直接从内存中读取，留出一个接口用来在需要时更新内存中的数据。

2021-11-15 12:06 UTC, zero-face commented
更改

2021-11-15 12:07 UTC, zero-face commented
格式风格统一

2021-11-15 12:13 UTC, zero-face commented
更改

2021-11-15 16:06 UTC, Jinxuyang reviewed
LGTM

2021-11-15 16:08 UTC, merged